"""M9 Category M: audit tampering (Phase 16). Reuses M6's existing
`AuditLedger`/`verify_chain` directly -- no second tamper-detection
mechanism is built here. What's new in M9 is confirming the SAME guarantee
holds for audit trails generated by genuinely adversarial scenarios (a
contradicted AI hypothesis, a blocked fee trap), not just the clean fixtures
`backend/tests/audit/test_verify_chain.py` already covers exhaustively (8+
tamper types, individually) -- see that file for the full tamper-type matrix,
not duplicated here.
"""
import json

import pytest

from app.audit.verify import verify_chain
from tests.adversarial.helpers import decide_one, find_payment_by_order, pick_by_archetype


@pytest.fixture()
def decision_env(tmp_path_factory):
    # Function-scoped override of the module-scoped conftest fixture --
    # this file deliberately tampers with its ledger in one test, so each
    # test here needs its own fresh, untampered database.
    from app.ai.provider import MockAIProvider
    from app.audit.ledger import AuditLedger
    from app.db.session import init_db, make_engine, make_session_factory
    from app.policy.approval import ApprovalWorkflowStore
    from tests.adversarial.helpers import DecisionEnvironment

    db_path = tmp_path_factory.mktemp("adv_audit_tampering") / "audit_tampering.db"
    engine = make_engine(db_path)
    init_db(engine)
    session = make_session_factory(engine)()
    return DecisionEnvironment(
        ledger=AuditLedger(session), approval_store=ApprovalWorkflowStore(), provider=MockAIProvider(), session=session,
    )


def test_tampering_an_event_from_a_genuine_adversarial_case_is_detected(mutated_dataset, ground_truth, decision_env):
    order_id = pick_by_archetype(ground_truth, "fee_mismatch", 0, not_adversarial=False)
    payment = find_payment_by_order(mutated_dataset, order_id)
    result = decide_one(mutated_dataset, payment.payment_id, decision_env)

    before = verify_chain(decision_env.session)
    assert before.valid is True

    events = decision_env.ledger.events_for_correlation(result.correlation_id)
    policy_event = next(e for e in events if e.event_type == "POLICY_EVALUATED")
    payload = json.loads(policy_event.payload_json)
    payload["decision"] = "SAFE_TO_RESOLVE"  # attacker attempts to rewrite the recorded decision
    policy_event.payload_json = json.dumps(payload, sort_keys=True)
    decision_env.session.commit()

    after = verify_chain(decision_env.session)
    assert after.valid is False
    assert after.reason == "HASH_MISMATCH"
    assert after.first_invalid_event_id == policy_event.event_id


def test_chain_stays_valid_when_untampered_across_many_adversarial_decisions(mutated_dataset, ground_truth, decision_env):
    for archetype, idx in [("fee_mismatch", 1), ("ambiguous_match", 1), ("duplicate", 1)]:
        order_id = pick_by_archetype(ground_truth, archetype, idx, not_adversarial=False)
        payment = find_payment_by_order(mutated_dataset, order_id)
        decide_one(mutated_dataset, payment.payment_id, decision_env)

    result = verify_chain(decision_env.session)
    assert result.valid is True
    assert result.events_checked > 0
